project_name: dev-server

build:
  main: main.go
  binary: dev-server
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386

  ignore:
    - goos: darwin
      goarch: 386
  ldflags:
    -X main.version=v{{.Version}}

archive:
  format_overrides:
    - goos: windows
      format: zip

brew:
  # Reporitory to push the tap to.
  github:
    owner: ThatTomPerson
    name: homebrew-tap


dockers:
  # You can have multiple Docker images.
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64

    binary: dev-server
    image_templates:
    - "ttpd/{{.ProjectName}}:v{{ .Tag }}"
    - "ttpd/{{.ProjectName}}:v{{ .Major }}"
    - "ttpd/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
    - "ttpd/{{.ProjectName}}:latest"
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"